version: '3.9'

services:

  db:
    image: postgres:17-alpine
    restart: always
    container_name: postgres
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  app:
    build:
      context: ./
      dockerfile: ./deploy/prod/Dockerfile
    restart: always
    container_name: app
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  celery_worker:
    build:
      context: ./
      dockerfile: ./deploy/celery/Dockerfile
    command: celery -A app.celery_tasks worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  celery_beat:
    build:
      context: ./
      dockerfile: ./deploy/celery/Dockerfile
    command: celery -A app.celery_tasks beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"


volumes:
  db:
  app: