version: '3.9'

services:

  db:
    image: postgres:17-alpine
    restart: always
    container_name: postgres
    volumes:
      - /mnt/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  elasticsearch:
    image: elasticsearch:8.18.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /mnt/data/elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 1m

  app:
    build:
      context: ./
      dockerfile: ./deploy/prod/Dockerfile
    restart: always
    container_name: app
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - elasticsearch
      - redis

  celery_worker:
    build:
      context: ./
      dockerfile: ./deploy/celery/Dockerfile
    command: celery -A app.celery_tasks worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  celery_beat:
    build:
      context: ./
      dockerfile: ./deploy/celery/Dockerfile
    command: celery -A app.celery_tasks beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - /mnt/data/redis:/data
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped


volumes:
  db:
  app:
  redis:
  elasticsearch: