"""billing fields for company

Revision ID: fccec13aa960
Revises: e71d6c1a2309
Create Date: 2025-05-11 14:05:14.200749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fccec13aa960'
down_revision: Union[str, None] = 'e71d6c1a2309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('last_payment_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('subscription_valid_until', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('payment_service', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('order_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'order_id')
    op.drop_column('companies', 'payment_service')
    op.drop_column('companies', 'subscription_valid_until')
    op.drop_column('companies', 'last_payment_at')
    # ### end Alembic commands ###
