"""billing fields for payment

Revision ID: f1184c5aa901
Revises: fccec13aa960
Create Date: 2025-05-11 14:06:18.758889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1184c5aa901'
down_revision: Union[str, None] = 'fccec13aa960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_service', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_service')
    # ### end Alembic commands ###
