"""name for channel

Revision ID: d34c8c32e243
Revises: 1153c9b3acc6
Create Date: 2025-04-16 17:41:51.609108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34c8c32e243'
down_revision: Union[str, None] = '1153c9b3acc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('name', sa.String(), server_default='Channel', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'name')
    # ### end Alembic commands ###
