"""billing

Revision ID: c8217af50292
Revises: a05d669a1d94
Create Date: 2025-05-10 16:07:15.518820

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8217af50292'
down_revision: Union[str, None] = 'a05d669a1d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('send_post_limit', sa.Integer(), nullable=False),
    sa.Column('ai_generation_limit', sa.Integer(), nullable=False),
    sa.Column('channels_limit', sa.Integer(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('reward_given', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('companies', sa.Column('current_plan_id', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('plan_started_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('balance_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('companies', sa.Column('referral_code', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('referred_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'companies', ['referred_by_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'plans', ['current_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'referred_by_id')
    op.drop_column('companies', 'referral_code')
    op.drop_column('companies', 'balance_tokens')
    op.drop_column('companies', 'plan_started_at')
    op.drop_column('companies', 'current_plan_id')
    op.drop_table('usages')
    op.drop_table('referrals')
    op.drop_table('payments')
    op.drop_table('plans')
    # ### end Alembic commands ###
