"""ai config

Revision ID: ee4735f361f4
Revises: bd92382e9f4f
Create Date: 2025-05-09 10:10:55.562583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4735f361f4'
down_revision: Union[str, None] = 'bd92382e9f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('temperature', sa.Float(), server_default='0', nullable=False),
    sa.Column('max_tokens', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('language', sa.String(), server_default='en', nullable=False),
    sa.Column('tone', sa.String(), server_default='neutral', nullable=False),
    sa.Column('writing_style', sa.String(), server_default='concise', nullable=False),
    sa.Column('custom_instructions', sa.String(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_config')
    # ### end Alembic commands ###
