"""scheduled timezone

Revision ID: a05d669a1d94
Revises: f37e89a91cf6
Create Date: 2025-05-09 15:41:57.486420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05d669a1d94'
down_revision: Union[str, None] = 'f37e89a91cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_ai_posts', sa.Column('timezone', sa.String(), server_default='UTC', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_ai_posts', 'timezone')
    # ### end Alembic commands ###
