"""delete cascade

Revision ID: 6cf4ae3fb07c
Revises: f1184c5aa901
Create Date: 2025-05-17 08:00:24.652678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf4ae3fb07c'
down_revision: Union[str, None] = 'f1184c5aa901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ai_config_company_id_fkey', 'ai_config', type_='foreignkey')
    op.drop_constraint('ai_config_channel_id_fkey', 'ai_config', type_='foreignkey')
    op.create_foreign_key(None, 'ai_config', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ai_config', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('auth_sessions_user_id_fkey', 'auth_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'auth_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('channel_logs_channel_id_fkey', 'channel_logs', type_='foreignkey')
    op.drop_constraint('channel_logs_post_id_fkey', 'channel_logs', type_='foreignkey')
    op.create_foreign_key(None, 'channel_logs', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'channel_logs', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('channels_company_id_fkey', 'channels', type_='foreignkey')
    op.create_foreign_key(None, 'channels', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('companies_referred_by_id_fkey', 'companies', type_='foreignkey')
    op.drop_constraint('companies_current_plan_id_fkey', 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'companies', ['referred_by_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'companies', 'plans', ['current_plan_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('payments_company_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('posts_company_id_fkey', 'posts', type_='foreignkey')
    op.drop_constraint('posts_channel_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'posts', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('referrals_referred_id_fkey', 'referrals', type_='foreignkey')
    op.drop_constraint('referrals_referrer_id_fkey', 'referrals', type_='foreignkey')
    op.create_foreign_key(None, 'referrals', 'companies', ['referrer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'referrals', 'companies', ['referred_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('scheduled_ai_posts_company_id_fkey', 'scheduled_ai_posts', type_='foreignkey')
    op.drop_constraint('scheduled_ai_posts_channel_id_fkey', 'scheduled_ai_posts', type_='foreignkey')
    op.create_foreign_key(None, 'scheduled_ai_posts', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scheduled_ai_posts', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sources_channel_id_fkey', 'sources', type_='foreignkey')
    op.drop_constraint('sources_company_id_fkey', 'sources', type_='foreignkey')
    op.create_foreign_key(None, 'sources', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sources', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('temp_data_user_id_fkey', 'temp_data', type_='foreignkey')
    op.create_foreign_key(None, 'temp_data', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('usages_company_id_fkey', 'usages', type_='foreignkey')
    op.create_foreign_key(None, 'usages', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_company_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_setting_user_id_fkey', 'users_setting', type_='foreignkey')
    op.create_foreign_key(None, 'users_setting', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_setting', type_='foreignkey')
    op.create_foreign_key('users_setting_user_id_fkey', 'users_setting', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_company_id_fkey', 'users', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'usages', type_='foreignkey')
    op.create_foreign_key('usages_company_id_fkey', 'usages', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'temp_data', type_='foreignkey')
    op.create_foreign_key('temp_data_user_id_fkey', 'temp_data', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.create_foreign_key('sources_company_id_fkey', 'sources', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('sources_channel_id_fkey', 'sources', 'channels', ['channel_id'], ['id'])
    op.drop_constraint(None, 'scheduled_ai_posts', type_='foreignkey')
    op.drop_constraint(None, 'scheduled_ai_posts', type_='foreignkey')
    op.create_foreign_key('scheduled_ai_posts_channel_id_fkey', 'scheduled_ai_posts', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key('scheduled_ai_posts_company_id_fkey', 'scheduled_ai_posts', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.create_foreign_key('referrals_referrer_id_fkey', 'referrals', 'companies', ['referrer_id'], ['id'])
    op.create_foreign_key('referrals_referred_id_fkey', 'referrals', 'companies', ['referred_id'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_channel_id_fkey', 'posts', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key('posts_company_id_fkey', 'posts', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_company_id_fkey', 'payments', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key('companies_current_plan_id_fkey', 'companies', 'plans', ['current_plan_id'], ['id'])
    op.create_foreign_key('companies_referred_by_id_fkey', 'companies', 'companies', ['referred_by_id'], ['id'])
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.create_foreign_key('channels_company_id_fkey', 'channels', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'channel_logs', type_='foreignkey')
    op.drop_constraint(None, 'channel_logs', type_='foreignkey')
    op.create_foreign_key('channel_logs_post_id_fkey', 'channel_logs', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('channel_logs_channel_id_fkey', 'channel_logs', 'channels', ['channel_id'], ['id'])
    op.drop_constraint(None, 'auth_sessions', type_='foreignkey')
    op.create_foreign_key('auth_sessions_user_id_fkey', 'auth_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'ai_config', type_='foreignkey')
    op.drop_constraint(None, 'ai_config', type_='foreignkey')
    op.create_foreign_key('ai_config_channel_id_fkey', 'ai_config', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key('ai_config_company_id_fkey', 'ai_config', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
