"""sources document

Revision ID: bd92382e9f4f
Revises: 37c46f8ebb8a
Create Date: 2025-05-03 13:00:32.248729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd92382e9f4f'
down_revision: Union[str, None] = '37c46f8ebb8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('document_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'document_id')
    # ### end Alembic commands ###
