"""sources limit

Revision ID: aad6f851c40f
Revises: c12ef994a322
Create Date: 2025-05-24 11:30:04.914938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad6f851c40f'
down_revision: Union[str, None] = 'c12ef994a322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('knowledge_base_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'knowledge_base_limit')
    # ### end Alembic commands ###
