"""ai config emoji

Revision ID: d50feab2ea17
Revises: ee4735f361f4
Create Date: 2025-05-09 10:14:47.354234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50feab2ea17'
down_revision: Union[str, None] = 'ee4735f361f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_config', sa.Column('emojis', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_config', 'emojis')
    # ### end Alembic commands ###
