"""billing trial

Revision ID: e71d6c1a2309
Revises: c8217af50292
Create Date: 2025-05-11 12:17:33.317293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e71d6c1a2309'
down_revision: Union[str, None] = 'c8217af50292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('is_trial', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'is_trial')
    # ### end Alembic commands ###
